# hatch shell

[project]
name = "milvus-example"
authors = [{ name = "IronCore Labs", email = "info@ironcorelabs.com" }]
requires-python = ">=3.9"
dependencies = [
  "ironcore-alloy>=0.13.1,<0.14",
  "sentence_transformers==2.3.1",
  "pymilvus==2.5.17",
]
dynamic = ["version"]
